UPDATE MY_USHAREDB.UPGRADE_TABLES SET dbname='MY_REPORT_DB1' WHERE dbname='MY_SOURCE_REPORT_DB1' ;
UPDATE MY_USHAREDB.UPGRADE_COLUMNS SET dbname='MY_REPORT_DB1' WHERE dbname='MY_SOURCE_REPORT_DB1' ;
UPDATE MY_USHAREDB.UPGRADE_STG_TBLS SET dbname='MY_STAGE_DB1' WHERE dbname='MY_SOURCE_STAGE_DB1';
UPDATE MY_USHAREDB.UPGRADE_STG_COLUMNS SET dbname='MY_STAGE_DB1' WHERE dbname='MY_SOURCE_STAGE_DB1';

UPDATE MY_USHAREDB.UPGRADE_TABLES SET dbname='MY_REPORT_DB2' WHERE dbname='MY_SOURCE_REPORT_DB2' ;
UPDATE MY_USHAREDB.UPGRADE_COLUMNS SET dbname='MY_REPORT_DB2' WHERE dbname='MY_SOURCE_REPORT_DB2' ;
UPDATE MY_USHAREDB.UPGRADE_STG_TBLS SET dbname='MY_STAGE_DB2' WHERE dbname='MY_SOURCE_STAGE_DB2';
UPDATE MY_USHAREDB.UPGRADE_STG_COLUMNS SET dbname='MY_STAGE_DB2' WHERE dbname='MY_SOURCE_STAGE_DB2';

UPDATE MY_USHAREDB.UPGRADE_TABLES SET dbname='MY_REPORT_DB3' WHERE dbname='MY_SOURCE_REPORT_DB3' ;
UPDATE MY_USHAREDB.UPGRADE_COLUMNS SET dbname='MY_REPORT_DB3' WHERE dbname='MY_SOURCE_REPORT_DB3' ;
UPDATE MY_USHAREDB.UPGRADE_STG_TBLS SET dbname='MY_STAGE_DB3' WHERE dbname='MY_SOURCE_STAGE_DB3';
UPDATE MY_USHAREDB.UPGRADE_STG_COLUMNS SET dbname='MY_STAGE_DB3' WHERE dbname='MY_SOURCE_STAGE_DB3';

UPDATE MY_USHAREDB.UPGRADE_TABLES SET dbname='MY_REPORT_DB4' WHERE dbname='MY_SOURCE_REPORT_DB4' ;
UPDATE MY_USHAREDB.UPGRADE_COLUMNS SET dbname='MY_REPORT_DB4' WHERE dbname='MY_SOURCE_REPORT_DB4' ;
UPDATE MY_USHAREDB.UPGRADE_STG_TBLS SET dbname='MY_STAGE_DB4' WHERE dbname='MY_SOURCE_STAGE_DB4';
UPDATE MY_USHAREDB.UPGRADE_STG_COLUMNS SET dbname='MY_STAGE_DB4' WHERE dbname='MY_SOURCE_STAGE_DB4';

UPDATE MY_USHAREDB.UPGRADE_TABLES SET dbname='MY_REPORT_DB5' WHERE dbname='MY_SOURCE_REPORT_DB5' ;
UPDATE MY_USHAREDB.UPGRADE_COLUMNS SET dbname='MY_REPORT_DB5' WHERE dbname='MY_SOURCE_REPORT_DB5' ;
UPDATE MY_USHAREDB.UPGRADE_STG_TBLS SET dbname='MY_STAGE_DB5' WHERE dbname='MY_SOURCE_STAGE_DB5';
UPDATE MY_USHAREDB.UPGRADE_STG_COLUMNS SET dbname='MY_STAGE_DB5' WHERE dbname='MY_SOURCE_STAGE_DB5';

UPDATE MY_USHAREDB.UPGRADE_TABLES SET dbname='MY_REPORT_DB6' WHERE dbname='MY_SOURCE_REPORT_DB6' ;
UPDATE MY_USHAREDB.UPGRADE_COLUMNS SET dbname='MY_REPORT_DB6' WHERE dbname='MY_SOURCE_REPORT_DB6' ;
UPDATE MY_USHAREDB.UPGRADE_STG_TBLS SET dbname='MY_STAGE_DB6' WHERE dbname='MY_SOURCE_STAGE_DB6';
UPDATE MY_USHAREDB.UPGRADE_STG_COLUMNS SET dbname='MY_STAGE_DB6' WHERE dbname='MY_SOURCE_STAGE_DB6';

UPDATE MY_USHAREDB.UPGRADE_TABLES SET dbname='MY_REPORT_DB7' WHERE dbname='MY_SOURCE_REPORT_DB7' ;
UPDATE MY_USHAREDB.UPGRADE_COLUMNS SET dbname='MY_REPORT_DB7' WHERE dbname='MY_SOURCE_REPORT_DB7' ;
UPDATE MY_USHAREDB.UPGRADE_STG_TBLS SET dbname='MY_STAGE_DB7' WHERE dbname='MY_SOURCE_STAGE_DB7';
UPDATE MY_USHAREDB.UPGRADE_STG_COLUMNS SET dbname='MY_STAGE_DB7' WHERE dbname='MY_SOURCE_STAGE_DB7';

