DROP TABLE HCCLGA_USHARE.UPGRADE_ISSUES_EXCLUDE;

CREATE MULTISET TABLE HCCLGA_USHARE.UPGRADE_ISSUES_EXCLUDE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
	 exclusion_type VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      tablename VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      columnname VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      databasename VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( exclusion_type ,tablename ,columnname ,databasename );

GRANT ALL ON HCCLGA_USHARE.UPGRADE_ISSUES_EXCLUDE TO PUBLIC;


INSERT INTO HCCLGA_USHARE.UPGRADE_ISSUES_EXCLUDE 
(exclusion_type,tablename,columnname)
SELECT 'Derived Columns',TRIM(A.TableName),TRIM(A.ColumnName)
FROM DBC.ColumnsV A
WHERE A.DatabaseName='HCCLGA' AND TRIM(A.TableName) NOT LIKE 'UPGR_%'
AND EXISTS
(
SELECT TRIM(B.TableName) FROM DBC.TablesV B
WHERE B.DatabaseName='HCCLPGA2_T'
AND TRIM(A.TableName)=TRIM(B.TableName)
)
MINUS

SELECT 'Derived Columns',TRIM(A.TableName),TRIM(A.ColumnName)
FROM DBC.ColumnsV A
WHERE A.DatabaseName='HCCLPGA2_T' 

;


INSERT INTO HCCLGA_USHARE.UPGRADE_ISSUES_EXCLUDE

SELECT 'Table Converted to View', TRIM(A.TableName),'' AS ColumnName,TRIM(A.DatabaseName)
FROM DBC.TablesV A
WHERE A.DatabaseName='HCCLGA' AND TRIM(A.TableName) NOT LIKE 'UPGR_%'
AND NOT EXISTS
(
SELECT TRIM(B.TableName) FROM DBC.TablesV B
WHERE B.DatabaseName='HCCLPGA2_T'
AND TRIM(A.TableName)=TRIM(B.TableName)
);


INSERT INTO HCCLGA_USHARE.UPGRADE_ISSUES_EXCLUDE
SELECT 'Table Not in COMPASS', TRIM(A.TableName),'' AS ColumnName,TRIM(A.DatabaseName)
FROM DBC.TablesV A
WHERE A.DatabaseName IN ('HCCLPGA2_S','HCCLPGA2_T')
AND NOT EXISTS
(
SELECT TRIM(B.TABLE_NAME) 
FROM HCCLPGA2_T.CLARITY_TBL B
WHERE TRIM(A.TableName)=TRIM(B.TABLE_NAME)
);



SELECT C.CHANGE_TYPE,A.* 
FROM HCCLGA_USHARE.DRYRUN_UPGRADE_ISSUES A
LEFT JOIN HCCLGA_USHARE.UPGRADE_ISSUES_EXCLUDE B 
		ON TRIM(A.tablename)=TRIM(B.tablename)
LEFT JOIN CLARITY_DBA_MAINT.CLARITY_UPG_CHG_LIST C 
		ON TRIM(A.tablename)=TRIM(C.UPG_TABLE_NAME) AND C.RUN_ID=7

WHERE 
	B.tablename IS NULL AND A.err_no NOT BETWEEN 901 AND 904
AND A.err_no <> 110 -- Ignore Staging Tables Present in Target but not in Source
AND TRIM(A.tablename) NOT LIKE  'U_0906_%'
AND TRIM(A.tablename) NOT LIKE  'T_0906_%'
AND TRIM(A.tablename) NOT LIKE 'BKUP_%'
AND TRIM(A.tablename) NOT LIKE 'BF1_%'
AND COALESCE(testing_rqrd,'') <> 'N'
ORDER BY A.err_no,A.tablename,A.columnname





