

SELECT DISTINCT
		 'DROP INDEX /*MY_TICKET*/' || TRIM(IND.IndexName) || ' ON ' || TRIM(IND.DatabaseName) || '.' ||  TRIM(IND.TableName) || ';' AS DROP_SEC_INDEX_SCRIPT
FROM DBC.Indices IND
JOIN CLARITY_DBA_MAINT.UPG_STG_LIST LIST ON TRIM(IND.TableName)=TRIM(LIST.STG_TABLE_NAME) AND LIST.CHANGE_TYPE='CREATE'
WHERE  IND.INDEXTYPE NOT IN ('P','Q','K') AND TRIM(IND.DatabaseName) LIKE ANY ('MY_DB','MYCPPMY_REGION%_S','MYCPPMY_REGION_TPF_S','MYCPPMY_REGION%_TPF_S');
   

   		 --IND.INDEXTYPE,
		 --IND.ColumnName,
		 --IND.ColumnPosition,
        /*CASE
          WHEN IND.INDEXTYPE = 'P' THEN 'NONPARTITIONEDPRIMARY'
          WHEN IND.INDEXTYPE = 'Q' THEN 'PARTITIONED PRIMARY'
          WHEN IND.INDEXTYPE = 'S' THEN 'SECONDARY'
          WHEN IND.INDEXTYPE = 'J' THEN 'JOIN INDEX'
          WHEN IND.INDEXTYPE = 'N' THEN 'HASH INDEX'
          WHEN IND.INDEXTYPE = 'K' THEN 'PRIMARY KEY'
          WHEN IND.INDEXTYPE = 'U' THEN 'UNIQUE CONSTRAINT'
          WHEN IND.INDEXTYPE = 'V' THEN 'VALUE ORDERED SECONDARY'
          WHEN IND.INDEXTYPE = 'H' THEN 'HASH ORDERED ALL COVERING SECONDARY'
          WHEN IND.INDEXTYPE = 'O' THEN 'VALUED ORDERED ALL COVERING SECONDARY'
          WHEN IND.INDEXTYPE = 'I' THEN 'ORDERING COLUMN OF A COMPOSITE SECONDARY INDEX'
          WHEN IND.INDEXTYPE = 'M' THEN 'MULTI-COLUMN STATISTICS'
          WHEN IND.INDEXTYPE = 'D' THEN 'DERIVED COLUMN PARTITION STATISTICS'
          ELSE NULL
         END  AS  INDTYPE */