DELETE	FROM  MY_TPF_STG.MY_TABLE ALL;
INSERT	INTO MY_TPF_STG.MY_TABLE
SELECT	*  
FROM	MY_STAGE_DB.MY_TABLE
WHERE	PAT_ID      IN
(
SELECT	pat_id
FROM	MY_USER_DB.x_patient_tpf
);
DELETE	
FROM	MY_STAGE_DB.MY_TABLE
WHERE	PAT_ID    IN
(
SELECT	pat_id
FROM	MY_USER_DB.x_patient_tpf
);
