SELECT
  TRIM(A.AUDIT_TABLE_NAME)
  || ',' || TRIM(CAST(B.AUDIT_VALUE AS BIGINT))
  || ',' || TRIM(CAST(A.AUDIT_VALUE AS BIGINT)) 
  || ',' || TRIM(CAST(B.AUDIT_VALUE AS BIGINT) - CAST(A.AUDIT_VALUE AS BIGINT)) 
  || ',' || TRIM(B.AUDIT_DATABASE_NAME) 
  || ',' || TRIM(A.AUDIT_DATABASE_NAME)
AS MIGRATION_REPORT

FROM CLARITY_DBA_MAINT.CLARITY_UPG_AUDIT A
JOIN CLARITY_DBA_MAINT.CLARITY_UPG_AUDIT B ON A.RUN_ID=B.RUN_ID 
AND B.AUDIT_ID - A.AUDIT_ID=100  AND B.RUN_ID=MY_RUN_ID  AND B.AUDIT_ID=204
JOIN CLARITY_DBA_MAINT.UPG_MIG_REPLACE_LIST C ON C.CHANGE_TYPE='M'
AND  A.AUDIT_TABLE_NAME=C.SOURCE_NAME AND A.AUDIT_DATABASE_NAME=C.SOURCE_DB
AND  B.AUDIT_TABLE_NAME=C.TEMP_NAME AND B.AUDIT_DATABASE_NAME=C.TEMP_DB

UNION ALL

SELECT
  TRIM(A.AUDIT_TABLE_NAME)
  || ',' || TRIM(CAST(0 AS BIGINT))
  || ',' || TRIM(CAST(A.AUDIT_VALUE AS BIGINT)) 
  || ',' || TRIM(CAST(0 AS BIGINT) - CAST(A.AUDIT_VALUE AS BIGINT)) 
  || ',' || TRIM('NOT MIGRATED') 
  || ',' || TRIM(A.AUDIT_DATABASE_NAME)
FROM CLARITY_DBA_MAINT.CLARITY_UPG_AUDIT A  
WHERE A.RUN_ID=MY_RUN_ID  AND A.AUDIT_ID=104
AND NOT EXISTS
(
SELECT TRIM(B.AUDIT_TABLE_NAME)
FROM CLARITY_DBA_MAINT.CLARITY_UPG_AUDIT B  
WHERE B.RUN_ID=MY_RUN_ID  AND B.AUDIT_ID=204
AND TRIM(A.AUDIT_TABLE_NAME)=TRIM(B.AUDIT_TABLE_NAME)
)

;


SELECT
  TRIM(A.AUDIT_TABLE_NAME)
  || ',' || TRIM(CAST(COALESCE(B.AUDIT_VALUE,0) AS BIGINT))
  || ',' || TRIM(CAST(A.AUDIT_VALUE AS BIGINT)) 
  || ',' || TRIM(CAST(COALESCE(B.AUDIT_VALUE,0) AS BIGINT) - CAST(A.AUDIT_VALUE AS BIGINT)) 
  || ',' || TRIM(COALESCE(B.AUDIT_DATABASE_NAME,'')) 
  || ',' || TRIM(COALESCE(C.AUDIT_DATABASE_NAME,''))
  || ',' || TRIM(CAST(COALESCE(C.AUDIT_VALUE,0) AS BIGINT))
  || ',' || TRIM(CAST(COALESCE(C.AUDIT_VALUE,0) AS BIGINT) - CAST(A.AUDIT_VALUE AS BIGINT)) 
AS CUTOVER_REPORT
  
FROM CLARITY_DBA_MAINT.CLARITY_UPG_AUDIT A
 JOIN CLARITY_DBA_MAINT.CLARITY_UPG_AUDIT B ON A.RUN_ID=B.RUN_ID 
AND B.AUDIT_ID - A.AUDIT_ID=100  AND B.RUN_ID=MY_RUN_ID  AND B.AUDIT_ID=204

JOIN CLARITY_DBA_MAINT.UPG_MIG_REPLACE_LIST T1 ON T1.CHANGE_TYPE='M'
AND  A.AUDIT_TABLE_NAME=T1.SOURCE_NAME AND A.AUDIT_DATABASE_NAME=T1.SOURCE_DB
AND  B.AUDIT_TABLE_NAME=T1.TEMP_NAME AND B.AUDIT_DATABASE_NAME=T1.TEMP_DB

 JOIN CLARITY_DBA_MAINT.CLARITY_UPG_AUDIT C ON C.RUN_ID=B.RUN_ID 
AND C.AUDIT_ID - B.AUDIT_ID=100  AND C.RUN_ID=MY_RUN_ID  AND C.AUDIT_ID=304

JOIN CLARITY_DBA_MAINT.UPG_MIG_REPLACE_LIST T2 ON T2.CHANGE_TYPE='M'
AND  C.AUDIT_TABLE_NAME=T2.SOURCE_NAME AND C.AUDIT_DATABASE_NAME=T2.SOURCE_DB
AND  B.AUDIT_TABLE_NAME=T2.TEMP_NAME AND B.AUDIT_DATABASE_NAME=T2.TEMP_DB

UNION ALL

SELECT
  TRIM(A.AUDIT_TABLE_NAME)
  || ',' || TRIM(CAST(0 AS BIGINT))
  || ',' || TRIM(CAST(A.AUDIT_VALUE AS BIGINT)) 
  || ',' || TRIM(CAST(0 AS BIGINT) - CAST(A.AUDIT_VALUE AS BIGINT)) 
  || ',' || TRIM('NOT MIGRATED') 
  || ',' || TRIM(A.AUDIT_DATABASE_NAME)
  || ',' || TRIM(CAST(0 AS BIGINT))
  || ',' || TRIM(CAST(0 AS BIGINT) - CAST(A.AUDIT_VALUE AS BIGINT)) 
FROM CLARITY_DBA_MAINT.CLARITY_UPG_AUDIT A  
WHERE A.RUN_ID=MY_RUN_ID  AND A.AUDIT_ID=104
AND NOT EXISTS
(
SELECT TRIM(B.AUDIT_TABLE_NAME)
FROM CLARITY_DBA_MAINT.CLARITY_UPG_AUDIT B  
WHERE B.RUN_ID=MY_RUN_ID  AND B.AUDIT_ID=204
AND TRIM(A.AUDIT_TABLE_NAME)=TRIM(B.AUDIT_TABLE_NAME)
)

;



SELECT
  TRIM(B.AUDIT_TABLE_NAME)
  || ',' || TRIM(COALESCE(B.AUDIT_DATABASE_NAME,'')) 
  || ',' || TRIM(CAST(COALESCE(B.AUDIT_VALUE,0) AS BIGINT))
  || ',' ||   TRIM(A.AUDIT_TABLE_NAME)
  || ',' || TRIM(A.AUDIT_DATABASE_NAME)
  || ',' || TRIM(CAST(A.AUDIT_VALUE AS BIGINT)) 
  || ',' || TRIM(CAST(COALESCE(B.AUDIT_VALUE,0) AS BIGINT) - CAST(A.AUDIT_VALUE AS BIGINT)) 

AS BACKUP_TABLE_COUNT_REPORT

FROM CLARITY_DBA_MAINT.CLARITY_UPG_AUDIT A
JOIN CLARITY_DBA_MAINT.CLARITY_UPG_AUDIT B ON A.RUN_ID=B.RUN_ID 
AND B.AUDIT_ID - A.AUDIT_ID=100  AND B.RUN_ID=MY_RUN_ID  AND B.AUDIT_ID=201
JOIN CLARITY_DBA_MAINT.UPG_BACKUP_REPLACE_LIST C ON C.BACKUP_TYPE='T'
AND  A.AUDIT_TABLE_NAME=C.SOURCE_NAME AND A.AUDIT_DATABASE_NAME=C.SOURCE_DB
AND  B.AUDIT_TABLE_NAME=C.BACKUP_NAME AND B.AUDIT_DATABASE_NAME=C.BACKUP_DB
;



SELECT
  TRIM(B.AUDIT_TABLE_NAME)
  || ',' || TRIM(COALESCE(B.AUDIT_DATABASE_NAME,'')) 
  || ',' || TRIM(CAST(COALESCE(B.AUDIT_VALUE,0)AS BIGINT))
  || ',' || TRIM(A.AUDIT_TABLE_NAME)
  || ',' || TRIM(A.AUDIT_DATABASE_NAME)
  || ',' || TRIM(CAST(A.AUDIT_VALUE AS BIGINT)) 
  || ',' || TRIM(CAST(COALESCE(B.AUDIT_VALUE,0) AS BIGINT) - CAST(A.AUDIT_VALUE AS BIGINT)) 

AS UPGR_VIEW_COUNT_REPORT

FROM CLARITY_DBA_MAINT.CLARITY_UPG_AUDIT A
JOIN CLARITY_DBA_MAINT.CLARITY_UPG_AUDIT B ON A.RUN_ID=B.RUN_ID 
AND B.AUDIT_ID - A.AUDIT_ID=100 AND B.RUN_ID=MY_RUN_ID AND B.AUDIT_ID=202
JOIN CLARITY_DBA_MAINT.UPG_BACKUP_REPLACE_LIST C ON C.BACKUP_TYPE='V'
AND  A.AUDIT_TABLE_NAME=C.SOURCE_NAME AND A.AUDIT_DATABASE_NAME=C.SOURCE_DB
AND  B.AUDIT_TABLE_NAME=C.BACKUP_NAME AND B.AUDIT_DATABASE_NAME=C.BACKUP_DB
;




SELECT
  TRIM(A.AUDIT_TABLE_NAME)
  || ',' || TRIM(A.AUDIT_DATABASE_NAME) 
  || ',' || TRIM(CAST(COALESCE(A.AUDIT_VALUE,0) AS BIGINT)) 
  || ',' || CASE WHEN B.AUDIT_VALUE IS NULL THEN '' ELSE TRIM(CAST(COALESCE(B.AUDIT_VALUE,0) AS BIGINT)) END
  || ',' || CASE WHEN B.AUDIT_VALUE IS NULL THEN '' ELSE TRIM(CAST(COALESCE(B.AUDIT_VALUE,0) AS BIGINT)- CAST(COALESCE(A.AUDIT_VALUE,0) AS BIGINT)) END

AS REASONABLE_VOLUME_REPORT

FROM CLARITY_DBA_MAINT.CLARITY_UPG_AUDIT A
LEFT JOIN CLARITY_DBA_MAINT.CLARITY_UPG_AUDIT B ON A.RUN_ID=B.RUN_ID 
AND (B.AUDIT_ID - A.AUDIT_ID=100) AND A.AUDIT_TABLE_NAME=B.AUDIT_TABLE_NAME

 WHERE  A.RUN_ID=MY_RUN_ID AND A.AUDIT_ID=105;

 
SELECT
  TRIM(A.TEST_CASE_NO) 
  || ',' || TRIM(A.TEST_CASE_NM) 
  || ',' || TRIM(COALESCE(A.EXPECTED_RESULT,0)) 
  || ',' || TRIM(COALESCE(A.ACTUAL_RESULT,0))
  || ',' || TRIM(COALESCE(A."DIFFERENCE",0))
AS VALIDATION_REPORT
FROM CLARITY_DBA_MAINT.CLARITY_UPG_VALIDATION A
 WHERE  A.RUN_ID=MY_RUN_ID
 ORDER BY 1;
 


