.SET ERRORLEVEL 3807 SEVERITY 0;

.LABEL STEP1

SELECT * FROM "MY_REPORT_DB"."MY_REPORT_TABLE" SAMPLE 1;

.IF ERRORCODE <> 0 THEN .GOTO WRAPUP;

.IF ACTIVITYCOUNT <> 0 THEN .GOTO STEP2;



.LABEL STEP2

SHOW TABLE "MY_REPORT_DB"."BKUP_MY_REPORT_TABLE";

.IF ERRORCODE <> 0 THEN .GOTO STEP3;

DROP TABLE "MY_REPORT_DB"."BKUP_MY_REPORT_TABLE";




.LABEL STEP3

CREATE TABLE "MY_REPORT_DB"."BKUP_MY_REPORT_TABLE" AS "MY_REPORT_DB"."MY_REPORT_TABLE" WITH DATA AND STATS;



.LABEL WRAPUP

