.EXPORT RESET; 
.EXPORT REPORT FILE = /users/MY_USER/dbmig/tempfiles/accdba_get_ddl.tmp;

SELECT TRIM(TableName) FROM DBC.TablesV WHERE TRIM(DatabaseName)='MY_DATABASE' AND TRIM(TableName)='MY_TABLE';

.IF ACTIVITYCOUNT <> 0 THEN .GOTO GET_DLL_MY_INDEX;

.GOTO WRAP_UP_MY_INDEX;

.LABEL GET_DLL_MY_INDEX

.EXPORT RESET; 
.EXPORT REPORT FILE = /users/MY_USER/dbmig/tempfiles/MY_OUTDDL_FILE;

SHOW MY_OBJECT "MY_DATABASE"."MY_TABLE";

.LABEL WRAP_UP_MY_INDEX
