SELECT 'MISSING IN $$SOURCE' || ',' || TRIM(TableName) AS MISSING_OBJECTS
FROM DBC.TablesV WHERE TRIM(DatabaseName) IN ('$$TARGET') AND TableKind IN ('T','V','P')
MINUS
SELECT 'MISSING IN $$SOURCE' || ',' || TRIM(TABNAME)
FROM CLARITY_DBA_MAINT.MIGRATION_LIST WHERE TRIM(DBNAME)IN ('$$SOURCE') AND TRIM(TABNAME) NOT LIKE 'UPGR_%';

SELECT 'MISSING IN $$TARGET' || ',' || TRIM(TABNAME) AS MISSING_OBJECTS
FROM CLARITY_DBA_MAINT.MIGRATION_LIST WHERE TRIM(DBNAME)IN ('$$SOURCE') AND TRIM(TABNAME) NOT LIKE 'UPGR_%'
MINUS
SELECT 'MISSING IN $$TARGET' || ',' || TRIM(TableName) AS MISSING_OBJECTS
FROM DBC.TablesV WHERE TRIM(DatabaseName) IN ('$$TARGET') AND TableKind IN ('T','V','P');

