 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/CLMSC1.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('NATL','CLMSC1'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/CLMSHI1.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('NATL','CLMSHI1'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/CLMSHI2.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('NATL','CLMSHI2'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/CLMSMA1.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('NATL','CLMSMA1'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/CLMSMA2.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('NATL','CLMSMA2'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/CLMSNW1.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('NATL','CLMSNW1'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/CLMSNW2.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('NATL','CLMSNW2'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/CLMSMAM.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('PROD','CLMSMAM'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/PROD_CO.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('PROD','PROD_CO'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/PROD_GA.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('PROD','PROD_GA'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/PROD_HI.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('PROD','PROD_HI'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/PROD_MA.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('PROD','PROD_MA'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/PROD_NC.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('PROD','PROD_NC'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/PROD_NW.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('PROD','PROD_NW'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/PROD_OH.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('PROD','PROD_OH'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/PROD_SC.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('PROD','PROD_SC'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/STSTMA2.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('PROD','STSTMA2'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/TESTMA2.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('PROD','TESTMA2'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/VALID_SC.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('PROD','VALID_SC'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/QA_NC.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('QA','QA_NC'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/CLMSMAM.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','CLMSMAM'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/DMDLNW2.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','DMDLNW2'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/DMDLNWV.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','DMDLNWV'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/NCAL_WITS2.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','NCAL_WITS2'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/NCAL_WITS3.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','NCAL_WITS3'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/PSUPGAM.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','PSUPGAM'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/PSUPHIM.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','PSUPHIM'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/REGNCO4.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','REGNCO4'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/REGNGAB.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','REGNGAB'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/REGNGAM.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','REGNGAM'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/REGNHIB.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','REGNHIB'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/REGNHIM.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','REGNHIM'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/RELSOHB.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','RELSOHB'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/RELSOHM.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','RELSOHM'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/RESC.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','RESC'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/SCAL_WITS.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','SCAL_WITS'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/STGN.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','STGN'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/STSTGAB.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','STSTGAB'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/STSTMA2.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','STSTMA2'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/TESTCO3.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','TESTCO3'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/TESTCO4.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','TESTCO4'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/TESTCO5.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','TESTCO5'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/TESTCO6.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','TESTCO6'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/TESTGA1.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','TESTGA1'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/TESTGAB.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','TESTGAB'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/TESTMA2.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','TESTMA2'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/TESTNW2.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','TESTNW2'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/TESTNWM.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','TESTNWM'); 
 .EXPORT RESET;
 .EXPORT REPORT FILE = /home/EDWDBA/dbmig/region/TESTOHM.profile
 EXEC CLARITY_DBA_MAINT.CLARITY_UPG_GET_ENV_DETAILS ('WITS','TESTOHM'); 
